### DISCUSSION TITLE
Github actions not running pest tests in parallel

### DISCUSSION THREAD

**Discussion by MickProPay** [pestphp/pest#1091] [Q&A]
I'm hoping someone can shine a light as to why when I upgraded to pest v 2 my git hub actions no longer wants to run my tests in parallel.

```
name: run-tests

on:
  pull_request:
    branches: [ development, master ]
  push:
    branches: ['release/**', 'hotfix/**']

jobs:
  test:
    runs-on: ${{ matrix.os }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: notmydb
          MYSQL_ROOT_PASSWORD: notmypassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [ 8.2 ]
        laravel: [ 10.* ]
        stability: [prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*

    name: Test P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACTIONS_PAT_WORKFLOW }}

      - name: Verify MySQL connection
        run: |
          mysql --version
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Install composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Install npm dependencies
        run: npm ci && npm run build && rm -rf node_modules

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests Unit
        run: php ./vendor/bin/pest --colors=always --parallel --processes=2

```

Error 
Tests\Unit\Actions\DeleteActionTest > can open th…  QueryException   
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists
