### DISCUSSION TITLE
Github action fails with exit code 139.

### DISCUSSION THREAD

**Discussion by ChristianPavilonis** [pestphp/pest#537] [Q&A]
For some reason my github action fails after hanging for almost 10 min after the tests finish running then fails with this error:
```
2603 Segmentation fault      (core dumped) vendor/bin/pest
Error: Process completed with exit code 139.
```

my workflow file
```yaml

name: Run Tests

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/pest
```

Any idea why this would be happening?
