### ISSUE TITLE
[Bug]: `option --coverage is ambiguous` in CI worker.

### ISSUE THREAD

**Issue by ElteHupkes** [pestphp/pest#1030]
### What Happened

My issue is very similar to #94 , except it happens GitLab CI, and the suggested fix doesn't apply (because the command doesn't include `--no-scripts` in the first place). This is the relevant CI entry:

```
test_api:
  stage: test
  coverage: /^\s*Cov:\s*\d+\.\d+?%$/
  variables:
    XDEBUG_MODE: "coverage"
    APP_ENV: "testing"
  cache:
    key: "${CI_JOB_NAME}-build"
    paths:
      - vendor
  artifacts:
    reports:
      junit: report.xml
    expire_in: 3 days
  only:
    - merge_requests
    - develop
    - staging
  script:
    - php -m
    - cp .env.gitlab-ci .env.testing
    - composer install
    - php artisan key:generate
    - php artisan optimize
    - vendor/bin/pest \
      --coverage \
      --log-junit report.xml \
      --colors=never \
      tests \
      --configuration phpunit.xml --colors=never --stop-on-failure
```

And the output:

```
....
$ vendor/bin/pest --coverage --log-junit report.xml --colors=never tests --configuration phpunit.xml --colors=never --stop-on-failure
   INFO  Option "--coverage" is ambiguous.
....
```

This started happening after upgrading to Laravel 10 / Pest 2 (latest version on both). Previously I had `--coverage-text` in the command, but while it runs with that, it doesn't give me any coverage output. Locally the command runs without any issues.

I added `cat vendor/pest-plugins.json` to the command list at some point to see if the autoloader ran, and that file is present and contains all the plugins. Still, the error implies that the Coverage plugin isn't invoked, because from what I can tell it would replace the `--coverage` option internally if it were. 

If anybody has an insight into why this is happening, I'm all ears.

### How to Reproduce

This is happening on all projects I've tried to upgrade so far, they're all set up with a CI setup similar to what's mentioned above. They all use the `php:8.1.6-fpm-bullseye` image with composer installed with:

`curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer`

### Pest Version

2.28.0

### PHP Version

8.1.6

### Operation System

Linux
