### ISSUE TITLE
To avoid Larastan errors : `test()` is it a correct replacement to `$this` ?

### ISSUE THREAD

**Issue by girardotcl** [pestphp/pest#1104]
## 🧑‍🏭 Context

I have security and code quality needs, i can't simply avoid errors with an ignore line in `phpstan.neon` like this :
```
    ignoreErrors:
        -
            message: '#Undefined variable: \$this#'
            path: */Modules/*/Tests/Feature/*
        -
            message: '#Call to an undefined method#'
            path: */Modules/*/Tests/Feature/*
```

I find the way by replacing all `$this` with `test()` :

- #### Before, with Larastan error
```php
beforeEach(fn() => $this->category = Category::factory()->create());

test('users can access categories edit route', function (User $user) {
    actingAs($user)
        ->get(route('admin.category.edit', ['category' => $this->category->id]))
        ->assertOk();
})
->with('my user dataset');

// ... other tests
```

- #### After, without larastan error
```php
beforeEach(fn() => test()->category = Category::factory()->create());

test('users can access categories edit route', function (User $user) {
    actingAs($user)
        ->get(route('admin.category.edit', ['category' => test()->category->id]))
        ->assertOk();
})
->with('my user dataset');

// ... other tests
```

I made some `dd()` and check the content, it seems ok.

## ❓Question

But before review all my test suite, I need a confirmation :

⚠️ **Is this a solid and sustainable solution from this package point of view ?** ⚠️ 

---

### Pest Version

2.8.1

### PHP Version

8.2.13

### Operation System

Windows & MacOS
