### ISSUE TITLE
[Bug]: Unknown option "--parallel". github workflow

### ISSUE THREAD

**Issue by emadbatwa** [pestphp/pest#1158]
### What Happened

![image](https://github.com/pestphp/pest/assets/41639197/891176fc-668f-4dfe-8cf5-2c468cef595c)

when run pest with --parallel flag on github action always get 
   INFO  Unknown option "--parallel".

the workflow file is :

```yml
name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_testing
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install composer Dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-suggest

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          
      - name: Verify Pest Version
        run: ./vendor/bin/pest --version

      - name: Execute backend tests (using custom composer script)
        run: ./vendor/bin/pest -c phpunit.pgsql.xml --no-coverage --parallel --processes=10

```

but if i remove --parallel i can run without any issue 

### How to Reproduce

create github workflow file
push to github
 see actions
 failed with error : 

   INFO  Unknown option "--parallel".

Error: Process completed with exit code 2.

### Pest Version

2.34.7

### PHP Version

8.3

### Operation System

Linux
