### ISSUE TITLE
[Bug]: This should not happen, on github actions

### ISSUE THREAD

**Issue by HichemTab-tech** [pestphp/pest#1358]
### What Happened

I got  Pest\Exceptions\ShouldNotHappen , when trying to execute `vendor/bin/pest --ci --coverage --coverage-clover=coverage.xml` on github actions.

![Image](https://github.com/user-attachments/assets/d7ad2a7d-1342-4125-b7c2-363f80a131be)

### How to Reproduce

In GitHub actions use : 
    ```
steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Clean vendor directory
        run: rm -rf vendor

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --ci --coverage --coverage-clover=coverage.xml
```

### Pest Version

3.7.4

### PHP Version

8.3.17

### Operation System

Linux
